In [1]:
#모듈 임포트s

import random
import os

## Test 1 ##

In [2]:
# Test 1

def dice():
  count= 0

  while(count >= 0):
    print("\n주사위를 던지자!")

    a = random.randint(1, 6)
    b = random.randint(1, 6)
    c = random.randint(1, 6)

    count += 1
    if a == b & b == c:
      print(a, b, c)
      print("빙고, 던진 횟수:" + str(count))
      break

    else:
      print(a, b, c)
      print("땡, 다시~")
    
  


In [3]:
dice()


주사위를 던지자!
2 3 1
땡, 다시~

주사위를 던지자!
1 6 3
땡, 다시~

주사위를 던지자!
2 5 1
땡, 다시~

주사위를 던지자!
4 6 3
땡, 다시~

주사위를 던지자!
3 6 1
땡, 다시~

주사위를 던지자!
5 5 1
땡, 다시~

주사위를 던지자!
4 6 4
땡, 다시~

주사위를 던지자!
6 4 2
땡, 다시~

주사위를 던지자!
4 2 6
땡, 다시~

주사위를 던지자!
2 5 2
땡, 다시~

주사위를 던지자!
4 3 2
땡, 다시~

주사위를 던지자!
1 3 3
땡, 다시~

주사위를 던지자!
3 3 6
땡, 다시~

주사위를 던지자!
6 6 3
땡, 다시~

주사위를 던지자!
3 2 3
땡, 다시~

주사위를 던지자!
3 2 3
땡, 다시~

주사위를 던지자!
3 3 2
땡, 다시~

주사위를 던지자!
6 1 1
땡, 다시~

주사위를 던지자!
3 5 5
땡, 다시~

주사위를 던지자!
6 5 3
땡, 다시~

주사위를 던지자!
5 4 3
땡, 다시~

주사위를 던지자!
4 6 1
땡, 다시~

주사위를 던지자!
5 1 4
땡, 다시~

주사위를 던지자!
3 6 5
땡, 다시~

주사위를 던지자!
4 1 1
땡, 다시~

주사위를 던지자!
2 2 3
땡, 다시~

주사위를 던지자!
3 1 1
땡, 다시~

주사위를 던지자!
3 5 1
땡, 다시~

주사위를 던지자!
6 5 2
땡, 다시~

주사위를 던지자!
5 1 6
땡, 다시~

주사위를 던지자!
1 5 1
땡, 다시~

주사위를 던지자!
4 2 4
땡, 다시~

주사위를 던지자!
5 3 6
땡, 다시~

주사위를 던지자!
1 3 4
땡, 다시~

주사위를 던지자!
6 4 5
땡, 다시~

주사위를 던지자!
3 2 4
땡, 다시~

주사위를 던지자!
5 4 1
땡, 다시~

주사위를 던지자!
4 3 2
땡, 다시~

주사위를 던지자!
4 1 6
땡, 다시~

주사위를 던지자!
3 6 5
땡, 다시~

주사위를 던지자!
4 1 5
땡, 다시~

주사위를 던지자!
2 6 6

## Test 2 ##

In [4]:
# Test 2
import time
food = ['피자', '치킨', '스테이크','된장찌개', '바나나', '파스타', '감자튀김']
food.sort()

def recommend():
  print("점심 메뉴를 추천해드립니다")
  print(food)
  time.sleep(1)
  menu = random.randint(0, len(food)-1)
  print("추천음식은 바로바로 --->", food[menu])

  ques = input("추가하고 싶은 음식이 있습니까? y/n")

  while(ques == 'y'):
    new = input("음식 이름(그만 추가하려면 q): ")

    if(new == 'q'):
      break

    food.append(new)

  food.sort()
  print(food) 
  print(food.index(input("찾는 음식은?")) + 1, '번째에 있습니다')




In [ ]:
recommend()

점심 메뉴를 추천해드립니다
추천음식은 바로바로 ---> 된장찌개
추가하고 싶은 음식이 있습니까? y/nn
['감자튀김', '된장찌개', '바나나', '스테이크', '치킨', '파스타', '피자']
찾는 음식은?피자
6 번째에 있습니다


## Test 3 ##

In [ ]:
#Test 3
list = []

def lottoFunc():
    lottery = random.randint(1, 45)
    return lottery

print("로또 추첨을 시작합니다!!!")

while True:
  if len(list) == 6:
    break

  lotto_num = lottoFunc() 

  if lotto_num not in list:
    list.append(lotto_num)
  
list.sort() 
print("이번 로또 번호 --->", end = " ")
print(list) 


로또 추첨을 시작합니다!!!
이번 로또 번호 ---> [11, 23, 32, 36, 40, 41]


## Test 4##

In [ ]:
# file os
f = open("/content/sample_data/Bigdata_4th_week.txt", 'w')
for i in range(1, 6):
  data = f"{i} 번째 줄입니다.\n"
  f.write(data)
f.close()

## Test5 ##

In [ ]:
f = open("/content/sample_data/Bigdata_4th_week.txt", 'r')
line = f.readline()
print(line)

while True:
  line = f.readline()
  if not line: #end of line?
    break
  print(line)

f.close()

1 번째 줄입니다.

2 번째 줄입니다.

3 번째 줄입니다.

4 번째 줄입니다.

5 번째 줄입니다.



In [ ]:
f = open("/content/sample_data/Bigdata_4th_week.txt", 'r')
lines = f.readlines()
print(lines)

for line in lines:
  print(line)

print(type(lines))
f.close()

['1 번째 줄입니다.\n', '2 번째 줄입니다.\n', '3 번째 줄입니다.\n', '4 번째 줄입니다.\n', '5 번째 줄입니다.\n']
1 번째 줄입니다.

2 번째 줄입니다.

3 번째 줄입니다.

4 번째 줄입니다.

5 번째 줄입니다.

<class 'list'>


In [ ]:
f = open("/content/sample_data/Bigdata_4th_week.txt", 'r')

data = f.read()
print(type(data))

print(data)

f.close()

<class 'str'>
1 번째 줄입니다.
2 번째 줄입니다.
3 번째 줄입니다.
4 번째 줄입니다.
5 번째 줄입니다.



## Test 6 ##

In [ ]:
#read csv, test6

import csv

In [ ]:
f = open("/content/sample_data/card.csv", encoding='UTF8')
data = csv.reader(f)
next(data)
data = list(data)

print('1번')
print(type(data))
print('2번')
print(len(data))
print('3번')
print(data[0])

print('4번')
print(data[:3]) # index 0 ~index 2 -> 3개

print('5번')
for row in data:
  print(row[0], row[5], row[6])

print('6번')
sum = 0
for row in data:
  date =row[0]
  month = date.split("-")[1]
  if month == '12':
    sum += int(row[6])
print('2019년 12월 총 이용금액:', sum,'원')

f.close()

## Test 7 ##

In [6]:
#Test 7, numpy
import numpy as np

In [8]:
ar1 = np.array([1, 2, 3, 4, 5])
print(ar1)

[1 2 3 4 5]


In [9]:
print(type(ar1))

<class 'numpy.ndarray'>


In [10]:
ar2 = np.array([[10, 20, 30], [40, 50, 60]])       

In [11]:
print(ar2)

[[10 20 30]
 [40 50 60]]


In [13]:
ar3 = np.arange(1, 11, 2)
ar4 = np.array([1, 2, 3, 4, 5, 6]).reshape(3, 2) #모양을 다시 만들자
ar5 = np.zeros((2, 3)) #0벡터 생성
ar6 = ar2[0:2, 0:2] #범위 지정, list slicing, 가로 0~1 , 세로 0~1로 슬라이싱할 것
ar7 = ar1 + 10
ar8 = np.dot(ar2, ar4) #dot product

In [14]:
print(ar3)

[1 3 5 7 9]


In [15]:
print(ar4)

[[1 2]
 [3 4]
 [5 6]]


In [16]:
print(ar5)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
print(ar6)

[[10 20]
 [40 50]]


In [18]:
print(ar7)

[11 12 13 14 15]


In [19]:
print(ar8)

[[220 280]
 [490 640]]
